baseURL = 'https://friendly-taffy-3a47a4.netlify.app'
languageCode = 'en-us'
title = 'aleja@ale'
theme = 'hugo-theme-console'


[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  

  [[params.navlinks]]
  name = "home/"
  url = "/"

  [[params.navlinks]]
  name = "reading/"
  url = "reading/"
  
 
